### PR TITLE
enable dynamic code point changes

### PR DESCRIPTION
**Pull request by baentsch**
Cloudflare uses different X25519 hybrid code points. This PR is to enable setting them dynamically for testing.

### CODE REVIEW

**Review by bhess — APPROVED** [review]

**Comment by dstebila** [comment]
Is there a reason you prefer to do them dynamically via environment variables rather than add them statically to the `oqs_group_list` array?

**Comment by baentsch** [comment]
> Is there a reason you prefer to do them dynamically via environment variables rather than add them statically to the oqs_group_list array?

These code points have been in the code for quite some time and without knowing whether someone already deployed sth with those values this seems the prudent thing to do. @bhess: You chose the values: Would you be OK we change them for good to the values chosen by Cloudflare?

**Comment by bhess** [comment]
> These code points have been in the code for quite some time and without knowing whether someone already deployed sth with those values this seems the prudent thing to do. @bhess: You chose the values: Would you be OK we change them for good to the values chosen by Cloudflare?

The code points were mainly placeholders for testing. Are the Cloudflare points registered (IANA, IETF..)?
If not it might be good to support multiple code points until there is a standard.

**Comment by baentsch** [comment]
> If not it might be good to support multiple code points until there is a standard.

This is exactly the reason why I did this PR: With this approach users have all flexibility in the world (and we don't have to change code -- either now or in the future when further alternatives become visible).

**Comment by baentsch** [comment]
@bhess @dstebila Would you want to (re-)review? Now, every single algorithm (126 -- a bit surprising even for me) can be re-configured by env var. Documentation also got a re-do.

**Comment by bhess** [comment]
> @bhess @dstebila Would you want to (re-)review? Now, every single algorithm (126 -- a bit surprising even for me) can be re-configured by env var. Documentation also got a re-do.

Looks good to me.

**Review by dstebila — APPROVED** [review]

**Pull request merged**
