### PR TITLE
Update codeowners

### LINKED ISSUE #457: Improve project maintainability
As per the [sibling issue in liboqs](https://github.com/open-quantum-safe/liboqs/issues/1843) triggered by a correct ["external" observation](https://github.com/open-quantum-safe/tsc/issues/45#issuecomment-2231978593) this issue is to suggest refactoring code along the lines of functions contributed/maintainable by more people than Yours Truly. This could be part of #375.

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #457.

Tagging specifically @bhess @thb-sb @feventura @iyanmv whether you're OK with these updates highlighting your contributions and codifying them explicitly in CODEOWNERS. The goal of this is to automatically request the right people in the future to help reviewing PRs on those files.

Any and all updates (preferably, your willingness to be listed in more sections of the CODEOWNER file -- but also fewer) very welcome. 

@feventura, please let me know if the association of yourself is too broad (all sig algs) -- I'd then try harder to factor out the composite sig code as I did for the hybrid KEM code of @bhess.

@feventura @iyanmv it seems you're lacking write access to the repo: If you'd state you're OK with these changes, I'll try to convince the LF admins to change this suitably.

### CODE REVIEW

**Comment by iyanmv** [comment]
@baentsch at least for me, don't waste time/effort to ask for write access ;) It was a one time small contribution. If in the future I do more, we can revisit that option.

**Review by thb-sb — APPROVED** [review]
SGTM, thank you :)

**Review by bhess — APPROVED** [review]

**Comment by feventura** [comment]
@baentsch I read a lot the code on all sigs, but I don't know the non-composite sigs well enough to answer questions for them.
That saying I think its too broad, but I don't mind answering "I can only answer questions for composite sigs" when I'm tagged with something while me, or someone else, work on the factoring out composite, like it is for hybrid KEM.

**Comment by baentsch** [comment]
> @baentsch If you would like access added for @feventura and @iyanmv, I can tack the config changes onto [this PR](https://github.com/open-quantum-safe/tsc/pull/59), and then you can approve and merge.

That would be great,  @SWilson4 !

**Comment by baentsch** [comment]
> @baentsch I read a lot the code on all sigs, but I don't know the non-composite sigs well enough to answer questions for them.
> That saying I think its too broad, but I don't mind answering "I can only answer questions for composite sigs" when I'm tagged with something while me, or someone else, work on the factoring out composite, like it is for hybrid KEM.

Thanks, @feventura . We'd then merge this as-is and create a separate issue to factor out Composites to make this better. I'd be grateful if you could take a first swing at implementing that, if you'd have time. If not, I'll try to do sth sensible (I hope).

**Comment by SWilson4** [comment]
> > @baentsch If you would like access added for @feventura and @iyanmv, I can tack the config changes onto [this PR](https://github.com/open-quantum-safe/tsc/pull/59), and then you can approve and merge.
> 
> That would be great, @SWilson4 !

All done, review and merge (if satisfactory) as you see appropriate!

**Pull request merged**
