### PR TITLE
Fix minor typos in documentation

### PR DESCRIPTION
**Pull request by johnma14**
Fixed minor typos and incorrect links in README.md and STANDARDS.md

### CODE REVIEW

**Comment by johnma14** [comment]
Looking at the failing CI tests for mac OS, looks like it is failing here: https://github.com/open-quantum-safe/oqs-provider/blob/mb-newpolicy/.circleci/config.yml#L304 and L307 while trying to pre-install OpenSSL v3.1. Currently the stable version supported for `brew install openssl@3` is v3.2. The supported versions for `brew install` are `openssl@3` (which is v3.2`), `openssl@3.0` and `openssl@1.1`. I can open another PR to fix it, if that helps.

**Comment by johnma14** [comment]
For reference, this is the [PR](https://github.com/open-quantum-safe/oqs-provider/commit/080c3dd2703a6b26f0aca12b265346a15f87c43e) where the changes were made.

**Comment by johnma14** [comment]
I just added the [skip ci] tag to skip all CI tests since this is a doc change. So all looks good now but the other issue with the CI tests on mac still exists. OpenSSL v3.2 was just released [last week](https://www.openssl.org/source/).

**Comment by baentsch** [comment]
> I can open another PR to fix it, if that helps.

That would be appreciated. Our approach is to immediately fix issues if we know there'd be something breaking (new, full) CI runs: Those should test new `oqsprovider` contributions, not the CI system.

**Review by baentsch — APPROVED** [review]
Thanks for these improvements!

**Comment by johnma14** [comment]
@baentsch @thb-sb I will go ahead and submit a PR right away to fix it. Thank you.

**Pull request merged**
