### PR TITLE
Clarify liboqs_DIR naming convention

### PR DESCRIPTION
**Pull request by ajbozarth**
As per discussion in #277 we want to clarify why the env var `liboqs_DIR` does not follow standard naming convention by using lowercase.

Fixes  #277

### CODE REVIEW

**Comment by ajbozarth** [comment]
@baentsch @thb-sb does this small addition to the docs look good to you two to clarify our decisions from #273 #277 #275 ?

**Comment by ajbozarth** [comment]
That's a good idea, what if I used this sentence instead:


This uses the [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) command in `cmake` which checks for local builds of a package at `<PackageName>_DIR`

**Review by baentsch — APPROVED** [review]
Thanks! LGTM. In future PRs, please tag documentation-only changes with "[skip ci]" to avoid running pointless testing. The environment says Thanks.

**Comment by ajbozarth** [comment]
> please tag documentation-only changes

good to know, many projects don't have that feature

**Comment by baentsch** [comment]
> > please tag documentation-only changes
> 
> good to know, many projects don't have that feature

Yup, many IT projects don't care about their environmental impact. There's a reason data  centers need about [200 TWh per year](https://www.statista.com/statistics/186992/global-derived-electricity-consumption-in-data-centers-and-telecoms), i.e., as much as [Israel, Switzerland and Finland](https://en.wikipedia.org/wiki/List_of_countries_by_electricity_production) _together generate_... OK, badly programmed AI probably is the biggest culprit, but just pointing to others is a cop out.

**Pull request merged**
