### PR TITLE
Add key type specific en- decoder

### LINKED ISSUE #562: i2d_PublicKey() fails with -1 for DILITHIUM2 key while using OQS provider with OpenSSL 3.2.1
### Discussed in https://github.com/orgs/open-quantum-safe/discussions/1968

<div type='discussions-op-text'>

<sup>Originally posted by **vk18anubhav** October 30, 2024</sup>
Hi Team,

I am generating a DILITHIUM2 key in my code using OpenSSL 3.2.1 by loading OQS provider as following 

```
EVP_PKEY *pkey = NULL;
EVP_PKEY_CTX *ctx = (EVP_PKEY_CTX *)NULL;

pkey = EVP_PKEY_new();

ctx = EVP_PKEY_CTX_new_from_name(libctx, "dilithium2", NULL);

EVP_PKEY_keygen_init(ctx);

EVP_PKEY_keygen(ctx, &pkey);
```

While converting the key to DER format using i2d_PublicKey() , it fails with -1 while i2d_PrivateKey() succeeds.

```
len = i2d_PublicKey(pkey, NULL); // First call itself fails

if(len < buffer->len)
buffer->len = i2d_PublicKey(pkey, buffer); // This also fails 
```

I tried debugging the issue by putting breakpoints on i2d_PublicKey(), i2d_PrivateKey() and sharing observations

```
int i2d_PublicKey(const EVP_PKEY *a, unsigned char **pp)
{
    if (evp_pkey_is_provided(a)) {
        static const struct type_and_structure_st output_info[] = {
            { "DER", "type-specific" },
            { "blob", NULL },    /* for EC */
            { NULL, }
        };
 
        return i2d_provided(a, EVP_PKEY_PUBLIC_KEY, output_info, pp);
    }

int i2d_PrivateKey(const EVP_PKEY *a, unsigned char **pp)
{
    if (evp_pkey_is_provided(a)) {
        static const struct type_and_structure_st output_info[] = {
            { "DER", "type-specific" },
            { "DER", "PrivateKeyInfo" },
            { NULL, }
        };
 
        return i2d_provided(a, EVP_PKEY_KEYPAIR, output_info, pp);
    }

```
 
- i2d_provided() calls OSSL_ENCODER_CTX_new_for_pkey(), OSSL_ENCODER_to_data() in loop for members of output_info
- OSSL_ENCODER_CTX_new_for_pkey () was using oqsprovider for getting libctx
- OSSL_ENCODER_to_data() returns doing nothing for output_type= DER, output_structure= "type-specific" for both private and public key.
- OSSL_ENCODER_to_data() succeeds for next output_type= DER, output_structure= “PrivateKeyInfo"  while it fails for output_type= blob, output_structure= NULL for public key and returns with -1

Can you please review on how I can resolve this ?</div>

### PR DESCRIPTION
**Pull request by wbeck10**
Encoding and decoding of oqs keys using type specific en- / decoding is not working.
This pull requests adds type specific key der en- / decoding.

This PR will solve Fixes #562
 
https://github.com/open-quantum-safe/oqs-provider/issues/562

### CODE REVIEW

**Comment by wbeck10** [comment]
I don't know why DCO check is failing. My primary EMail is beck.wolfgang@oracle.com.

**Comment by baentsch** [comment]
> I don't know why DCO check is failing. My primary EMail is [beck.wolfgang@oracle.com](mailto:beck.wolfgang@oracle.com).

DCO "validation" is nothing I ever understood. @ryjones can you help?

**Review by baentsch — CHANGES_REQUESTED** [review]
Thanks very much for these additional en/decoders @wbeck10 ! May I ask how you did that code without using the jinja2 code generator? Or did you use it? If so, please be sure to also add the changed fragment files to the commit, e.g., https://github.com/open-quantum-safe/oqs-provider/blob/main/oqs-template/oqsprov/oqs_decode_der2key.c/decoder_make.fragment adding all "type_specific_keypair" MAKE_DECODER statements. If not, please use them so this gets auto-generated on every new change of algorithms when running `oqs-template/generate.py`.

**Comment by ryjones** [comment]
@baentsch @wbeck10 if you [look here](https://github.com/open-quantum-safe/oqs-provider/pull/596/checks?check_run_id=34573205936) you will see `No sign-off matches the author or committer`

if you look:
```
commit 92c5639424a5f847a22e86cf76daf28f20844113 (HEAD -> encdec)
Author: wbeck10 <beck.wolfgang10@gmail.com>
Date:   Wed Dec 4 03:07:57 2024 +0000

    Add key type specific en- decoder
    
    Signed-off-by: Wolfgang Beck <beck.wolfgang@oracle.com>

```

The Author and Signed-off-by do not match.

**Comment by wbeck10** [comment]
> @baentsch @wbeck10 if you [look here](https://github.com/open-quantum-safe/oqs-provider/pull/596/checks?check_run_id=34573205936) you will see `No sign-off matches the author or committer`
> 
> if you look:
> 
> ```
> commit 92c5639424a5f847a22e86cf76daf28f20844113 (HEAD -> encdec)
> Author: wbeck10 <beck.wolfgang10@gmail.com>
> Date:   Wed Dec 4 03:07:57 2024 +0000
> 
>     Add key type specific en- decoder
>     
>     Signed-off-by: Wolfgang Beck <beck.wolfgang@oracle.com>
> ```
> 
> The Author and Signed-off-by do not match.

This is my old EMail I've used before working in Oracle, I've changed my primary EMail to the Oracle EMail a long time ago. Maybe a bug in Github?

**Comment by SWilson4** [comment]
> This is my old EMail I've used before working in Oracle, I've changed my primary EMail to the Oracle EMail a long time ago. Maybe a bug in Github?

I don't believe GitHub sets the author email for a commit, I think that would be up to your git config. (`git config user.email`)

**Comment by ryjones** [comment]
> > This is my old EMail I've used before working in Oracle, I've changed my primary EMail to the Oracle EMail a long time ago. Maybe a bug in Github?
> 
> I don't believe GitHub sets the author email for a commit, I think that would be up to your git config. (`git config user.email`)

correct

**Comment by wbeck10** [comment]
Will create a new one

**Comment by wbeck10** [comment]
New PR:

https://github.com/open-quantum-safe/oqs-provider/pull/597

**Pull request closed without merging**
