### PR TITLE
Address some Static Analysis Issues #519

### PR DESCRIPTION
**Pull request by ashman-p**
Addresses some static analysis errors reported by Coverity tool.

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
These changes all make sense and improve code safety. Thanks @ashman-p !

**Comment by ashman-p** [comment]
Thanks @baentsch, i am not sure if i needed another approval, so adding a few more reviewers.

**Comment by baentsch** [comment]
No, 1 review is sufficient in a project with as many maintainers :-) Do you have permissions to merge?

**Review by dstebila — APPROVED** [review]

**Comment by baentsch** [comment]
@ashman-p Is it possible that you merged this without squashing? The commit history at least got substantially longer that I'd figure it should be. If no, please do so in the future to keep things together that belong together. Thanks!

**Comment by ashman-p** [comment]
> @ashman-p Is it possible that you merged this without squashing? The commit history at least got substantially longer that I'd figure it should be. If no, please do so in the future to keep things together that belong together. Thanks!

I think that was the case. I will remember to squash be the merge.

**Pull request merged**
