### PR TITLE
Clarify OpenSSL 1.1.1 Status

### PR DESCRIPTION
**Pull request by xloem**
Take it or leave it.  #19

### CODE REVIEW

**Comment by baentsch** [comment]
Thanks for your interest in our work. The proposed addition is a duplication of what is covered in more detail in and by [the "Status" section](https://github.com/open-quantum-safe/oqs-provider/blob/main/README.md#status), though.

**Comment by xloem** [comment]
Just to clarify here, I see the information is implied by the bottom of the section you reference, but it does not seem clear to me at all.  In my opinion, ideally there would be a clear and obvious path for every visitor to switch to quantum-informed algorithms.  However, I understand your work is on the cutting edge and most of your visitors will be intellectuals with sharper eyes than I have.  Thank you for your needed work.

**Comment by baentsch** [comment]
Thanks very much for this needed "external" view: By no means our work is meant for "sharp eyed intellectuals" only. To the contrary we spent a lot of effort to make things as easy as possible to consume (e.g., doing [docker images](https://hub.docker.com/search?q=openquantumsafe&type=image)) for people with less time and interest to dive into all details of PQ/QS crypto.

You are pointing out a relevant shortcoming that I only now realized myself: The OpenSSL provider had been part of the OpenSSL fork _and_ is *not* properly documented at the project overview at https://openquantumsafe.org (in particular [the part on TLS](https://openquantumsafe.org/applications/tls/)). We'll fix this. 

As the various OQS subprojects further may have non-obvious interdependencies for the initial user it probably is a good idea to provide additional pointers from the github READMEs to [the project overview site](https://openquantumsafe.org) to explain those to the "unwary". Will notify you of updates via comment here. Thanks again for your time to make us aware of this.

**Comment by xloem** [comment]
Thanks for your links.  Looks like https://github.com/open-quantum-safe/oqs-engine was what I was wondering the status of, and it needs a dev to be able to continue.

Apologies if I have taken your time.

**Pull request closed without merging**
