### PR TITLE
Enable `LIBOQS_DIR` as cache entry and environment variable.

### PR DESCRIPTION
**Pull request by ghost**
Fix https://github.com/open-quantum-safe/oqs-provider/issues/273

`liboqs_DIR` is a CMake cache entry to hint CMake about the location of liboqs
CMake package.

However, being able to use `LIBOQS_DIR` (full capitalized) would be more
convenient.

This PR adds the ability to use either `liboqs_DIR` as a cache entry, `liboqs_DIR`
as an environment variable, `LIBOQS_DIR` as a cache entry and `LIBOQS_DIR`
as an env variable.

Tests were also added to make sure that these variables are well taken
by CMake during the configuration stage.

### CODE REVIEW

**Review by baentsch — COMMENTED** [review]
Thanks very much for all this work, particularly the new CI test for this "chose any capitalization" feature -- I'm just not sure why it's "green": When looking at it, it seems to have failed, e.g. open "Test oqsprovider" twisty at https://github.com/open-quantum-safe/oqs-provider/actions/runs/6430477110/job/17461513594 (?)

**Comment by baentsch** [comment]
> let's see what happens!

Not the right thing :-/ Besides, why doesn't this get reported as a CI error? And: Would an actual build and test not be prudent?

**Comment by ajbozarth** [comment]
I've tried running this with multiple build commands and none of them work, even the one that did previously.

Usually I put the liboqs_DIR env var before the cmake command, but I also tried putting it inline as well (though this has never worked for me even on main).

Here's the four commands and tried and the error (red text) associated with each of them

1. `liboqs_DIR=$WORKSPACE/oqs cmake -DCMAKE_INSTALL_PREFIX=$WORKSPACE/oqs-provider -DOPENSSL_ROOT_DIR=$WORKSPACE -DCMAKE_BUILD_TYPE=Release -S . -B _build` (this is the one that works on `main`)
```
CMake Error at CMakeLists.txt:101 (message):
  `libos_DIR` environment variable does not match the value previously set
  ('/Users/ajbozarth/workspace/quantum/openssl_build/oqs' !=
  '/Users/ajbozarth/workspace/quantum/oqs-provider').
```
2. `cmake -Dliboqs_DIR=$WORKSPACE/oqs -DCMAKE_INSTALL_PREFIX=$WORKSPACE/oqs-provider -DOPENSSL_ROOT_DIR=$WORKSPACE -DCMAKE_BUILD_TYPE=Release -S . -B _build`
```
CMake Error at CMakeLists.txt:87 (message):
  `liboqs_DIR` cache entry and `LIBOQS_DIR` environment variable mismatch
  ('/Users/ajbozarth/workspace/quantum/openssl_build/oqs' !=
  '/Users/ajbozarth/workspace/quantum/oqs-provider').
```
3. `LIBOQS_DIR=$WORKSPACE/oqs cmake -DCMAKE_INSTALL_PREFIX=$WORKSPACE/oqs-provider -DOPENSSL_ROOT_DIR=$WORKSPACE -DCMAKE_BUILD_TYPE=Release -S . -B _build` (note that this error is the one that I see when run options 2, 3 and 4 on `main`)
```
CMake Error at CMakeLists.txt:111 (find_package):
  By not providing "Findliboqs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "liboqs", but
  CMake did not find one.

  Could not find a package configuration file provided by "liboqs" with any
  of the following names:

    liboqsConfig.cmake
    liboqs-config.cmake

  Add the installation prefix of "liboqs" to CMAKE_PREFIX_PATH or set
  "liboqs_DIR" to a directory containing one of the above files.  If "liboqs"
  provides a separate development package or SDK, be sure it has been
  installed.
```
4. `cmake -DLIBOQS_DIR=$WORKSPACE/oqs -DCMAKE_INSTALL_PREFIX=$WORKSPACE/oqs-provider -DOPENSSL_ROOT_DIR=$WORKSPACE -DCMAKE_BUILD_TYPE=Release -S . -B _build`
```
CMake Error at CMakeLists.txt:90 (message):
  `LIBOQS_DIR` cache entry and `LIBOQS_DIR` environment variable mismatch
  ('/Users/ajbozarth/workspace/quantum/openssl_build/oqs' != '').
```

**Comment by baentsch** [comment]
> even the one that did previously.

Well, previously we were using `cmake` as intended. Now we try to do something going against its conventions. Apologies to @thb-sb to have suggested you "quickly" do this PR.

**Comment by baentsch** [comment]
> We may better keep the current variable as it follows CMake rules.

Fully agree. Do you want to update this PR (maybe just add a documentation clarification instead of the new code) or just close it?

**Pull request closed without merging**
