### PR TITLE
Move the clang-format check from CircleCI to GitHub actions.

### PR DESCRIPTION
**Pull request by ghost**
Move the clang-format check from CircleCI to GitHub actions.

Related to https://github.com/open-quantum-safe/oqs-provider/issues/248.

Signed-off-by: thb-sb <thomas.bailleux@sandboxquantum.com>

### CODE REVIEW

**Review by bhess — COMMENTED** [review]
When moving this over to Github CI, would it make sense to make the heavier jobs dependent on the coding style check succeeding, such as done in liboqs?
https://github.com/open-quantum-safe/liboqs/blob/d183ed326609a0e0087f339b0eb948de9d33035d/.github/workflows/unix.yml#L42

**Comment by baentsch** [comment]
> make the heavier jobs dependent on the coding style check succeeding

Indeed, the environment would say Thanks.

That said, OQS so far already did much more than "typical projects" in this regards/not blindly running CI in the various projects -- but there's still quite some way to go: What about OQS "institutes" this? Ask contributors to use "[skip ci]" as often as possible, do (CI) spot checks before doing "heavy lifting", possibly move more CI to the weekly tests, reduce the repetition of the profiling runs, etc? I know, [just like project openness probably another low priority issue to the LinuxFoundation masters of OQS](https://github.com/PQCA/governance/issues/1#issuecomment-1987311408), but maybe worthwhile a thought?

**Review by bhess — APPROVED** [review]
Thank you Thomas, LGTM.

> What about OQS "institutes" this? Ask contributors to use "[skip ci]" as often as possible, do (CI) spot checks before doing "heavy lifting", possibly move more CI to the weekly tests, reduce the repetition of the profiling runs, etc?

I really like the idea @baentsch. I hope you don't mind that I created an [issue](https://github.com/open-quantum-safe/tsc/issues/5) about the topic.

**Comment by baentsch** [comment]
> I hope you don't mind that I created an https://github.com/open-quantum-safe/tsc/issues/5 about the topic.

I never mind good ideas :-) And if it's not posted by me, our new LinuxFoundation masters might actually react positively about them.

**Pull request merged**
