### PR TITLE
OSX path fixes

### PR DESCRIPTION
**Pull request by baentsch**
Fixes [more OSX path errors](https://github.com/open-quantum-safe/oqs-provider/issues/132#issuecomment-1495877053). Thanks @mouse07410 for "staying on" this.

### CODE REVIEW

**Comment by mouse07410** [comment]
Good start, but insufficient. For example, on MacOS it still tends to set `LD_LIBRARY_PATH` to some silly-weird `XXXX/.local/lib64`, **despite LD_LIBRARY PATH being set and passed to the script**.

Please ensure that your script prints out **all** the env vars it uses.

**Comment by baentsch** [comment]
> it still tends to set LD_LIBRARY_PATH to some silly-weird XXXX/.local/lib64, despite LD_LIBRARY PATH being explicitly set and passed to the script

That should only happen if `OPENSSL_INSTALL` has been set _and_ if this directory exists. Weird. Do you maybe have some leftovers from previous test runs around? Did you try passing the "-F" (full cleanup) parameter before running the `fullbuild` script?

> Please ensure that your script prints out all the env vars it uses.

I intentionally refrained from that to not overwhelm the "casual" user with what in effect is debug output. Would it be an option to "auto-magically" activate that if any of the "OQSPROV|SIG|KEM" debug env vars were set when running the script(s)?

**Comment by mouse07410** [comment]
> Do you maybe have some leftovers from previous test runs around? 

I'm trying to avoid that by `rm -rf tmp/*`, but am not sure.

> Did you try passing the "-F" (full cleanup) parameter before running the `fullbuild` script?

Passing parameter "-F" to where? 

Also, it is my understanding that `fullbuild` would clone OpenSSL and liboqs - so I _never_ run that script, ever.

> I intentionally refrained from that to not overwhelm the "casual" user with what in effect is debug output.

In my opinion, this is a mistake. For a "casual" user, there won't be much difference between ignoring printout of 4 env vars vs. ignoring, say, 8 env vars. And I don't think your scripts use even as much as 8. But, again, **all** of those used need to be shown - to see what value they actually took for the run.

> Would it be an option to "auto-magically" activate that if any of the "OQSPROV|SIG|KEM" debug env vars were set when running the script(s)?

Not sure. Better then nothing - but I think we're splitting hairs now. It's not like we're debating printing out just plaintext+ciphertext of AES vs. output of every AES inner round. 
Just add those 2-4 missing vars and be done with it. ;-)

**Comment by baentsch** [comment]
> Passing parameter "-F" to where?

fullbuild.sh. It then cleans all dependencies and binaries

> Also, it is my understanding that fullbuild would clone OpenSSL and liboqs 

That understanding isn't quite right (any more): It (now) builds OpenSSL only if OPENSSL_BRANCH is set or if no `openssl` v3 is found. You're right in that it did this (before) when the directory `openssl` was missing. `liboqs` is required for building `oqsprovider` and fetched (if not already present).

>  there won't be much difference between ignoring printout of 4 env vars vs. ignoring, say, 8 env vars

Well, just checked: On OSX you have a point: There, `env` outputs "just" 15 vars. On Linux, it's 60 (!).

> Just add those 2-4 missing vars and be done with it. ;-)

No problem with that. Which ones?

**Comment by mouse07410** [comment]
> > Also, it is my understanding that fullbuild would clone OpenSSL and liboqs
>
> That understanding isn't quite right (any more): It (now) builds OpenSSL only if OPENSSL_BRANCH
>  is set or if no openssl v3 is found. You're right in that it did this (before) when the directory openssl
> was missing.

Ok, fine - however:

> `liboqs` is required for building `oqsprovider` **and fetched (if not already present)**.

And here's where I have a problem - how the scripts figure whether `liboqs` is installed, and if it is - then where.
I _absolutely don't want _ `fullbuild.sh` to fetch and build another LIBOQS merely because it doesn't know any better.

So, unless/until there's a compelling reason to, I'd prefer to avoid `fullbuild.sh`.

> > Just add those 2-4 missing vars and be done with it. ;-)
>
> No problem with that. Which ones?

```sh
DYLD_LIBRARY_PATH
LD_LIBRARY_PATH
LIBOQS_BRANCH
LIBOQS_SRC_DIR
OPENSSL_APP
OPENSSL_BRANCH
OPENSSL_CONF
OPENSSL_DIR
OPENSSL_INSTALL
OPENSSL_MODULES
OPENSSL_ROOT_DIR
```

Might need more, but this seems comprehensive enough.

**Comment by baentsch** [comment]
> the fact that it insists on LD_LIBRARY_PATH being set (and exits if it's empty).

Thanks to @mouse07410 suggestion these "nanny instructions" have now been removed: If (DY)LD_LIBRARY_PATH is not set in the component tests, testing will not stop anymore. In turn, if (DY)LD_LIBRARY_PATH are set when starting testing, those settings will not be changed and any failures are due to the user :)

This PR also excludes testing for "OpenSSL 3.0.1" as it is unable to properly register new signature algorithms (after loading `oqsprovider`).

@dstebila @bhess Please check and approve as I'd like to finally tag a release now.

**Pull request merged**
